import { useMemo, useState } from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'
import './Home.css'

function Home({ onExplore, onSignIn, selected, onToggleIngredient, navigate }) {
  const heroIngredients = [{ name: 'Spinach', position: 'spinach' }, { name: 'Chicken Breast', position: 'chicken' }, { name: 'Garlic', position: 'garlic' }, { name: 'Tomato', position: 'tomato' }]
  const [focusedIngredient, setFocusedIngredient] = useState('Spinach')
  const match = useMemo(() => Math.min(100, 58 + selected.length * 8), [selected.length])
  const selectedHeroIngredients = heroIngredients.filter(({ name }) => selected.includes(name)).map(({ name }) => name)
  const toggleFromImage = (name) => { setFocusedIngredient(name); onToggleIngredient(name) }
  return <div className="app"><Header activePage="home" onExplore={onExplore} onHome={() => window.scrollTo(0, 0)} onSignIn={onSignIn} /><main><section className="landing-hero container"><div><span className="landing-label">◌ Culinary clarity</span><h1>Cook with what you have.</h1><p>Tap ingredients on the board to build your pantry, then discover recipes that fit your kitchen.</p><button className="landing-cta" onClick={onExplore}>Get started <span>→</span></button></div><div className="landing-image interactive-hero"><img src="https://lh3.googleusercontent.com/aida-public/AB6AXuCDtMbyy9W3mR5lhy6SaQs4gO4Ottzi6qmzoubFykhqRa1WHxdQY39H_BD-tIa8Wab_i-36EsFhIYxPKSgkcOEpSjj7oxGufgs8fShy-pkfmYpmaP9MdgGHpNdkIpwpCqYArqVT0gNreVkVH5LxlM-sJK_ZJNkqTzz7FB9q83mbnoF6bHgWsipWlnKibmY5GqUfHJM1vUfeyxeFs1FzOnspqEGpYd4HtqSxPi6ECsCDPil-7rhQ2ybh" alt="Fresh ingredients prepared for cooking"/>{heroIngredients.map(({ name, position }) => <button type="button" key={name} className={`ingredient-hotspot ${position} ${selected.includes(name) ? 'selected' : ''}`} onClick={() => toggleFromImage(name)} onMouseEnter={() => setFocusedIngredient(name)} aria-pressed={selected.includes(name)}><i>{selected.includes(name) ? '✓' : '+'}</i><span>{name}</span></button>)}<div className="ingredient-status"><small>Kitchen board</small><strong>{focusedIngredient}</strong><p>{selected.includes(focusedIngredient) ? 'Added to your pantry' : 'Tap to add to your pantry'}</p><div>{selectedHeroIngredients.length ? selectedHeroIngredients.map((item) => <em key={item}>✓ {item}</em>) : <em>Choose an ingredient</em>}</div></div><span><b>{match}%</b> Match</span><p className="hero-hint">Explore the ingredients on your board</p></div></section><section className="landing-steps"><h2>Culinary clarity in three steps</h2><p>Make better meals from the groceries you already own.</p><div className="landing-step-grid container"><article><span>01</span><h3>Input ingredients</h3><p>Open your fridge and add what you see.</p></article><article><span>02</span><h3>Get matches</h3><p>Recipes rank themselves by your kitchen.</p></article><article><span>03</span><h3>Cook &amp; share</h3><p>Follow simple steps and make it yours.</p></article></div></section></main><Footer navigate={navigate} /></div>
}

export default Home
