import { useState } from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'
import './InfoPages.css'

function PageShell({ children, navigate, title, intro }) {
  return <div className="app info-app"><Header activePage="" onHome={() => navigate('home')} onExplore={() => navigate('explore')} onCommunity={() => navigate('community')} onSignIn={() => navigate('signin')} /><main className="info-main container"><section className="info-hero"><span className="landing-label">Flavor Fusion</span><h1>{title}</h1><p>{intro}</p></section>{children}</main><Footer navigate={navigate} /></div>
}

const steps = [{ number: '01', title: 'Add ingredients', text: 'Tell us what is already in your kitchen—one ingredient at a time or a whole pantry.' }, { number: '02', title: 'Get matches', text: 'Discover recipes ranked by what you have, with clear notes about anything missing.' }, { number: '03', title: 'Cook & share', text: 'Make the recipe yours, save favorites, and swap ideas with fellow home cooks.' }]

export function About({ navigate }) { return <PageShell navigate={navigate} title="Good food starts with what you have." intro="Flavor Fusion turns the ingredients already in your kitchen into practical, delicious inspiration."><section className="step-flow">{steps.map((step) => <article key={step.number}><span>{step.number}</span><h2>{step.title}</h2><p>{step.text}</p><button onClick={() => navigate(step.number === '03' ? 'community' : 'explore')}>{step.number === '03' ? 'Visit Community' : 'Start exploring'} →</button></article>)}</section><section className="feature-section"><div><span className="label">BUILT FOR REAL KITCHENS</span><h2>Less guesswork. More meals you’ll love.</h2><p>We make everyday cooking feel a little lighter by connecting your pantry to useful recipe ideas and a warm community of cooks.</p></div><div className="team-card"><span>FF</span><div><h3>Made by food people</h3><p>A small team of designers, engineers, and enthusiastic home cooks building tools we use every day.</p></div></div></section></PageShell> }

const privacySections = [['Information we collect', 'We collect the account details you provide, such as your name and email, plus information needed to keep your Flavor Fusion profile working.'], ['Your pantry and saved recipes', 'Ingredients you add and recipes you save are stored to personalize matches and make your next visit easier. You can update these details at any time.'], ['Community content', 'Posts, comments, photos, and recipe links you choose to share may be visible to other community members. Please share thoughtfully and only post content you have the right to use.'], ['AI features', 'When you use AI-powered recipe ideas, your prompts and relevant pantry context may be processed to generate a useful response and improve the feature.'], ['How we use data', 'We use information to provide the product, personalize recipe matches, protect the community, understand performance, and communicate important updates.']]
const termsSections = [['Using your account', 'Keep your login information secure and use Flavor Fusion lawfully. You are responsible for activity that happens through your account.'], ['Recipes and recommendations', 'Recipe suggestions are for inspiration. Check ingredients, nutrition, allergies, cooking temperatures, and food safety before cooking.'], ['Community content', 'You retain ownership of what you post, while giving Flavor Fusion permission to display it within the service. Do not post harmful, unlawful, or infringing content.'], ['AI-generated recipes', 'AI output can be incomplete or inaccurate. Review every recommendation and use your own judgment, especially around dietary needs and food safety.'], ['Your responsibilities', 'Use the service respectfully, do not interfere with others, and do not misuse content, systems, or other users’ information.'], ['Disclaimers', 'Flavor Fusion is provided as a helpful cooking tool and is not medical, nutritional, or professional food-safety advice.']]

function Accordion({ items }) { const [open, setOpen] = useState(0); return <div className="accordion">{items.map(([heading, copy], index) => <article key={heading} className={open === index ? 'open' : ''}><button onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}><span>{heading}</span><b>{open === index ? '−' : '+'}</b></button>{open === index && <p>{copy}</p>}</article>)}</div> }

export function PolicyPage({ navigate }) { return <PageShell navigate={navigate} title="Privacy, in plain language." intro="Here is how Flavor Fusion handles the information that helps make your cooking experience personal and useful."><Accordion items={privacySections} /><p className="policy-note">Last updated: August 2024. Questions about privacy? Visit our Help Center.</p></PageShell> }
export function Terms({ navigate }) { return <PageShell navigate={navigate} title="Terms of Service" intro="These simple terms explain the shared expectations that help keep Flavor Fusion useful, welcoming, and safe."><Accordion items={termsSections} /><p className="policy-note">By using Flavor Fusion, you agree to these terms and to use good judgment in the kitchen.</p></PageShell> }

const helpTopics = [{ category: 'Ingredients', question: 'How do I add ingredients?', answer: 'Go to Explore, type an ingredient into your pantry, then choose it from the suggestions. Your matches update instantly.' }, { category: 'Recipes', question: 'How are recipe matches ranked?', answer: 'Recipes are ranked by the ingredients you already have. Each card highlights missing items so you can decide what to cook.' }, { category: 'Saved Recipes', question: 'Where can I find saved recipes?', answer: 'Use the Saved link in the navigation. Saved items stay associated with your browser until you remove them.' }, { category: 'Grocery List', question: 'How do I use missing ingredients?', answer: 'Each recipe shows what is missing. Use that list as a quick shopping reminder before cooking.' }, { category: 'Community', question: 'How do I share a post?', answer: 'Open Community, write your update, optionally add a photo or recipe link, then select Post. You can also like, save, comment, and share others’ posts.' }, { category: 'AI Recipe Generator', question: 'How should I use AI recipe ideas?', answer: 'Use AI ideas as a starting point, then verify allergens, dietary needs, ingredient quantities, and safe cooking temperatures yourself.' }]

export function HelpCenter({ navigate }) { const [query, setQuery] = useState(''); const [selected, setSelected] = useState(helpTopics[0]); const [sent, setSent] = useState(false); const filtered = helpTopics.filter((topic) => `${topic.category} ${topic.question} ${topic.answer}`.toLowerCase().includes(query.toLowerCase())); return <PageShell navigate={navigate} title="How can we help?" intro="Find a quick answer or browse the topics that make Flavor Fusion tick."><section className="help-search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search help topics..." aria-label="Search help topics"/><span>⌕</span></section><section className="help-grid"><div className="help-categories">{filtered.map((topic) => <button key={topic.category} onClick={() => setSelected(topic)} className={selected.category === topic.category ? 'active' : ''}><b>{topic.category}</b><small>{topic.question}</small></button>)}{!filtered.length && <p>No help topics match that search.</p>}</div><article className="help-answer"><span className="label">{selected.category}</span><h2>{selected.question}</h2><p>{selected.answer}</p><button onClick={() => navigate(selected.category === 'Community' ? 'community' : 'explore')}>Take me there →</button></article></section><section className="contact-card"><div><h2>Still need help?</h2><p>Send us a note and our kitchen crew will get back to you.</p></div><button onClick={() => setSent(true)}>{sent ? 'Message received ✓' : 'Contact support'}</button></section></PageShell> }

const roles = [{ title: 'Product Designer', type: 'Remote · Full-time', description: 'Shape clear, kind experiences that help cooks go from ingredients to dinner with confidence.', requirements: ['3+ years designing digital products', 'Strong systems thinking', 'A love for practical, human-centered details'] }, { title: 'Frontend Engineer', type: 'Remote · Full-time', description: 'Build fast, polished interfaces for the people who use Flavor Fusion in their everyday kitchens.', requirements: ['Strong React and modern CSS', 'Thoughtful accessibility practice', 'Comfort collaborating across disciplines'] }, { title: 'Community Lead', type: 'Hybrid · Full-time', description: 'Help our growing community feel welcoming, useful, and full of genuine cooking inspiration.', requirements: ['Experience in community programs', 'Excellent writing and moderation instincts', 'A hands-on, empathetic approach'] }]
export function Careers({ navigate }) { const [open, setOpen] = useState(null); const [applied, setApplied] = useState(''); return <PageShell navigate={navigate} title="Come cook up something great." intro="We’re building a kinder, more useful way to decide what’s for dinner. Join us."><section className="careers-intro"><h2>Open roles</h2><p>We value curiosity, care, and teammates who know the best ideas can come from anywhere.</p></section><div className="roles">{roles.map((role, index) => <article key={role.title} className={open === index ? 'open' : ''}><button className="role-heading" onClick={() => setOpen(open === index ? null : index)}><div><h2>{role.title}</h2><p>{role.type}</p></div><b>{open === index ? '−' : '+'}</b></button>{open === index && <div className="role-detail"><p>{role.description}</p><h3>You’ll bring</h3><ul>{role.requirements.map((item) => <li key={item}>{item}</li>)}</ul><button onClick={() => setApplied(role.title)}>Apply for this role →</button></div>}</article>)}</div>{applied && <p className="application-note">Thanks for your interest in the {applied} role. Your application link is ready—our team will be in touch.</p>}</PageShell> }
